name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt install nasm

    - name: Build
      run: make

    - name: Upload generated file as artifact
      uses: actions/upload-artifact@v4
      with:
        name: generated-file
        path: hdd.img
